# CMake generated Testfile for 
# Source directory: /Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/modules/superres
# Build directory: /Users/runewind/Documents/GitHub/Master/object detection/build_opencv/modules/superres
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_superres "/Users/runewind/Documents/GitHub/Master/object detection/build_opencv/bin/opencv_test_superres" "--gtest_output=xml:opencv_test_superres.xml")
set_tests_properties(opencv_test_superres PROPERTIES  LABELS "Main;opencv_superres;Accuracy" WORKING_DIRECTORY "/Users/runewind/Documents/GitHub/Master/object detection/build_opencv/test-reports/accuracy" _BACKTRACE_TRIPLES "/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVUtils.cmake;1686;add_test;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVModule.cmake;1292;ocv_add_test_from_target;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVModule.cmake;1074;ocv_add_accuracy_tests;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/modules/superres/CMakeLists.txt;9;ocv_define_module;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/modules/superres/CMakeLists.txt;0;")
add_test(opencv_perf_superres "/Users/runewind/Documents/GitHub/Master/object detection/build_opencv/bin/opencv_perf_superres" "--gtest_output=xml:opencv_perf_superres.xml")
set_tests_properties(opencv_perf_superres PROPERTIES  LABELS "Main;opencv_superres;Performance" WORKING_DIRECTORY "/Users/runewind/Documents/GitHub/Master/object detection/build_opencv/test-reports/performance" _BACKTRACE_TRIPLES "/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVUtils.cmake;1686;add_test;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVModule.cmake;1203;ocv_add_test_from_target;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVModule.cmake;1075;ocv_add_perf_tests;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/modules/superres/CMakeLists.txt;9;ocv_define_module;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/modules/superres/CMakeLists.txt;0;")
add_test(opencv_sanity_superres "/Users/runewind/Documents/GitHub/Master/object detection/build_opencv/bin/opencv_perf_superres" "--gtest_output=xml:opencv_perf_superres.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_superres PROPERTIES  LABELS "Main;opencv_superres;Sanity" WORKING_DIRECTORY "/Users/runewind/Documents/GitHub/Master/object detection/build_opencv/test-reports/sanity" _BACKTRACE_TRIPLES "/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVUtils.cmake;1686;add_test;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVModule.cmake;1204;ocv_add_test_from_target;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/cmake/OpenCVModule.cmake;1075;ocv_add_perf_tests;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/modules/superres/CMakeLists.txt;9;ocv_define_module;/Users/runewind/Documents/GitHub/Master/object detection/opencv-3.4.15/modules/superres/CMakeLists.txt;0;")
